fix: too few arguments to webinix_set_profile
When following the C++ hello world tutorial, the first example
immediately fails to compile due to an error in hte C++ header file.

```
In file included from main.cpp:1:
webinix.hpp: In member function ‘void webinix::window::set_proxy(std::string_view) const’:
webinix.hpp:202:26: error: too few arguments to function ‘void webinix_set_profile(size_t, const char*, const char*)’
  202 |         webinix_set_profile(webinix_window, proxy_server.data());
      |         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from webinix.hpp:21:
webinix.h:422:19: note: declared here
  422 | WEBINIX_EXPORT void webinix_set_profile(size_t window, const char* name, const char* path);
```